DATABASE = "database.txt"
DAILY_TIMES_EAT = 3
WORKING_DAYS = 7
MONTH_DAYS = 31
MONTH_WEEKS = 4.42
MONTHS_YEAR = 12
ANIMAL_INCOME_DAILY = 60
FOODS_PRIZE = {"meat": 4, "others": 2, "foliage": 2, "grass": 2, "bamboo": 2}
RELAX_PERIOD = 6
NAMES = ["Gosho", "Pesho", "Misho", "Lubo", "Maya", "Stefi", "Jane", "Petranka", "Vasilka", "Ivanka", "Vasil", "Ivan", "Oktay"]
